name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug_Clang, Release_Clang]

    runs-on: ubuntu-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
            
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y clang-15

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3.0.0

    - name: Configure CMake
      run: cmake --preset ${{ matrix.configuration }} -S ${{github.workspace}}

    - name: Build
      run: cmake --build --preset ${{ matrix.configuration }}

    #- name: Test
    #  run: ctest --output-on-failure